# This environment lists all the explicit dependencies. 
# Note that it is NOT directly used by binder.
# You should use it to generate the frozen environment.yml with:
# 
# $ conda env export > environment.yml
#
# Then, at the bottom of the file, change the part that looks like
#
# - pip:
#   - mdsapt==...
#
# to 
#
# - pip:
#   - git+https://github.com/calpolyccg/MDSAPT.git@v2.0.0


name: mdsaptdemo
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<=3.11
  - mdsapt
  - nglview

